export const QUESTIONS = [
  "What's the most embarrassing thing that's happened to you?",
  "What's your biggest fear?",
  "What's the worst date you've ever been on?",
  "What's the most trouble you've ever been in?",
  "What's your biggest regret?",
  "What's the most embarrassing thing in your search history?",
  "What's the worst lie you've ever told?",
  "What's the most embarrassing thing you've done while drunk?",
  "What's the most embarrassing thing you've done to impress someone?",
  "What's the most embarrassing thing you've done in public?",
  "What's the most embarrassing thing you've done at work?",
  "What's the most embarrassing thing you've done at school?",
  "What's the most embarrassing thing you've done in front of your family?",
  "What's the most embarrassing thing you've done in front of your friends?",
  "What's the most embarrassing thing you've done in front of your crush?",
  "What's the most embarrassing thing you've done in front of your boss?",
  "What's the most embarrassing thing you've done in front of your teacher?",
  "What's the most embarrassing thing you've done in front of your parents?",
  "What's the most embarrassing thing you've done in front of your siblings?",
  "What's the most embarrassing thing you've done in front of your partner?"
]; 